#!/usr/bin/env python3
# GENERATED by scripts/generate_fmp_client.py — do not edit.
# Source of truth: scripts/fmp_client/ (core_template.py.tmpl, registry.py, extensions/).
# Regenerate: python3 scripts/generate_fmp_client.py
"""
FMP API Client for IBD Distribution Day Monitor

Provides rate-limited access to Financial Modeling Prep API endpoints.

Features:
- Rate limiting (0.3s between requests)
- Automatic key failover via fmp_compat (repo-root transport)
- Session caching for duplicate requests
- API call budget enforcement
- Batch company profile support
- Earnings calendar and historical price fetching
"""

import os
import sys
import time
from datetime import date, timedelta
from pathlib import Path
from typing import Optional

try:
    import requests
except ImportError:
    print("ERROR: requests library not found. Install with: pip install requests", file=sys.stderr)
    sys.exit(1)

SKILL_ROOT = Path(__file__).resolve().parents[3]
if str(SKILL_ROOT) not in sys.path:
    sys.path.insert(0, str(SKILL_ROOT))

try:
    from fmp_compat import fmp_get_typed, key_override, request_count
except ImportError:  # standalone .skill install without the repo-root module
    fmp_get_typed = None


# --- FMP endpoint: stable only. FMP retired v3 for non-legacy keys on
# 2025-08-31; a v3 URL requested through fmp_compat is rewritten back to the
# equivalent stable endpoint anyway (see `_V3_TO_STABLE` in the repo-root
# fmp_compat.py), so a second "v3 fallback" entry here was never a distinct
# endpoint — it was a second, rate-limited query of the SAME stable endpoint
# (WPP-20260827-012). ---


def _stable_hist_url(base, symbols_str, params):
    """stable/historical-price-eod/full?symbol=^GSPC&timeseries=80

    `timeseries` is passed through unchanged — fmp_compat's own
    `_prepare_params_for_url` converts it into a from/to range plus an
    internal `_tm_limit` truncation bound before the request is made.
    """
    params["symbol"] = symbols_str
    return base, params


_FMP_ENDPOINTS = {
    "historical": [
        ("https://financialmodelingprep.com/stable/historical-price-eod/full", _stable_hist_url),
    ],
}


class ApiCallBudgetExceeded(Exception):
    """Raised when the API call budget has been exhausted."""

    pass


class FMPClient:
    """Client for Financial Modeling Prep API with rate limiting, caching, and budget control"""

    BASE_URL = "https://financialmodelingprep.com/api/v3"
    RATE_LIMIT_DELAY = 0.3  # 300ms between requests

    _ENDPOINT_FAILURE_THRESHOLD = 3  # disable endpoint after N consecutive failures

    def __init__(self, api_key: Optional[str] = None, max_api_calls: int = 200):
        self.api_key = api_key or os.getenv("FMP_API_KEY")
        if not self.api_key:
            raise ValueError(
                "FMP API key required. Set FMP_API_KEY environment variable "
                "or pass api_key parameter."
            )
        self.cache = {}
        self.last_call_time = 0
        self.rate_limit_reached = False
        self.retry_count = 0
        self.max_retries = 1
        self.api_calls_made = 0
        self.max_api_calls = max_api_calls
        # Circuit breaker: track consecutive failures per endpoint URL prefix
        self._endpoint_failures: dict[str, int] = {}
        self._disabled_endpoints: set[str] = set()
        # Most recent transport-level failure reason; set by _rate_limited_get
        # so _request_with_fallback can surface suppressed errors even when
        # an endpoint was called with quiet=True.
        self._last_error: Optional[str] = None

    def _raw_stable_get(self, url: str, params: dict) -> Optional[dict]:
        """Thin standalone fallback when fmp_compat is not importable — a
        `.skill` archive bundles this file but not the repo-root
        `fmp_compat.py` (verified via `unzip -l`). One request, no key
        failover, no v3 rung; sets `_last_error` on any miss."""
        try:
            response = requests.get(url, params=self._raw_params(url, params), timeout=30)
            if response.status_code == 200:
                return self._raw_fold(url, params, response.json())
        except (requests.exceptions.RequestException, ValueError):
            pass
        self._last_error = "fmp_compat unavailable: raw stable GET, no failover"
        return None

    def _raw_params(self, url: str, params: dict) -> dict:
        """Standalone path only: the stable EOD endpoint ignores `timeseries`,
        so bound the payload with a from/to range the way fmp_compat's
        `_prepare_params_for_url` does (2x calendar days covers N trading
        days); the row truncation happens in `_raw_fold`."""
        prepared = {k: v for k, v in params.items() if k != "timeseries"}
        if "historical-price-eod/full" in url and "timeseries" in params:
            today = date.today()
            prepared["from"] = (today - timedelta(days=int(params["timeseries"]) * 2)).isoformat()
            prepared["to"] = today.isoformat()
        prepared["apikey"] = self.api_key
        return prepared

    def _raw_fold(self, url: str, params: dict, data):
        """Standalone path only: fold the stable EOD flat list into the
        `{"symbol", "historical": [...]}` shape `_request_with_fallback`
        validates (fmp_compat does this on the shared path). Fail CLOSED on a
        malformed row — a shortened series that still looks complete is
        laundered evidence (WPP-20260902-002). Non-EOD payloads and the
        `historicalStockList` dict pass through unchanged (codex nested gate
        r1 P1, 2026-09-06)."""
        if "historical-price-eod/full" not in url or not isinstance(data, list):
            return data
        symbol = str(params.get("symbol", ""))
        norm = symbol.replace("-", ".")
        rows = []
        for row in data:
            if not isinstance(row, dict) or "date" not in row:
                self._last_error = "malformed EOD row in standalone payload — refusing the series"
                return None
            row_symbol = row.get("symbol") or symbol
            if row_symbol.replace("-", ".") != norm:
                continue
            rows.append({k: v for k, v in row.items() if k != "symbol"})
        limit = params.get("timeseries")
        if limit is not None and int(limit) > 0:
            rows = rows[: int(limit)]
        return {"symbol": symbol, "historical": rows}

    def _rate_limited_get(
        self, url: str, params: Optional[dict] = None, quiet: bool = False
    ) -> Optional[dict]:
        """Make a rate-limited GET request with budget enforcement.

        Raises:
            ApiCallBudgetExceeded: When api_calls_made >= max_api_calls
        """
        if self.api_calls_made >= self.max_api_calls:
            raise ApiCallBudgetExceeded(
                f"API call budget exhausted: {self.api_calls_made}/{self.max_api_calls} calls used"
            )

        self._last_error = None
        if self.rate_limit_reached:
            self._last_error = "daily rate limit already reached"
            return None

        if params is None:
            params = {}

        elapsed = time.time() - self.last_call_time
        if elapsed < self.RATE_LIMIT_DELAY:
            time.sleep(self.RATE_LIMIT_DELAY - elapsed)

        if fmp_get_typed is None:
            if not getattr(self, "_warned_no_fmp_compat", False):
                print(
                    "WARNING: fmp_compat unavailable (standalone install) — "
                    "using a single stable GET with no key failover",
                    file=sys.stderr,
                )
                self._warned_no_fmp_compat = True
            self.last_call_time = time.time()
            self.api_calls_made += 1
            return self._raw_stable_get(url, params)

        # A caller-supplied key differing from the ambient FMP_API_KEY is
        # scoped to this call only; FMP_FALLBACK_API_KEY is never touched.
        override = self.api_key if self.api_key != os.environ.get("FMP_API_KEY") else None
        before = request_count()
        with key_override(override):
            data, reason = fmp_get_typed(
                url,
                params=params,
                timeout=30,
                max_retries_per_key=1,
                max_attempts=self.max_api_calls - self.api_calls_made,
            )
        # fmp_get_typed may retry and fail over keys: charge every HTTP
        # attempt it actually made against the budget, never a flat 1.
        self.api_calls_made += max(1, request_count() - before)
        self.last_call_time = time.time()
        self._last_error = reason
        if data is None:
            # Only the 429 daily-quota signal latches the run-wide breaker;
            # 402/403/soft-quota is usually a free-tier entitlement gap and
            # `unreachable` is a transport blip — neither should stop the run.
            if reason == "rate_limited:429":
                self.rate_limit_reached = True
            if not quiet:
                print(f"ERROR: {url} failed ({reason})", file=sys.stderr)
        return data

    def _request_with_fallback(self, endpoint_key, symbols_str, extra_params=None):
        """Query the stable FMP endpoint(s); the loop shape stays even though
        each endpoint list is now a single entry (fmp_compat already rewrites
        a v3 URL back to the identical stable endpoint, so a second "v3
        fallback" rung was never a distinct endpoint — WPP-20260827-012).
        Non-last endpoints are called with quiet=True so the user isn't
        alarmed by an expected failure when another entry will catch it — but
        when a non-last endpoint DOES fail, a WARN line is emitted explaining
        why we're falling back. Otherwise users only see the (often misleading)
        last-endpoint error and have no clue what really went wrong.
        """
        params = dict(extra_params) if extra_params else {}
        endpoints = _FMP_ENDPOINTS[endpoint_key]
        is_single = "," not in symbols_str

        for i, (base_url, url_builder) in enumerate(endpoints):
            # Circuit breaker: skip endpoints with too many consecutive failures
            if base_url in self._disabled_endpoints:
                continue

            url, final_params = url_builder(base_url, symbols_str, dict(params))
            is_last = i == len(endpoints) - 1
            data = self._rate_limited_get(url, final_params, quiet=not is_last)
            if not data:  # falsy (None, [], {}) — try next endpoint
                self._record_endpoint_failure(base_url)
                self._warn_fallback(base_url, is_last, self._last_error)
                continue

            # Shape validation: reject truthy-but-wrong-shape responses
            valid = True
            shape_issue: Optional[str] = None
            if endpoint_key == "historical":
                if not isinstance(data, dict):
                    valid = False
                    shape_issue = "expected dict"
                elif "historicalStockList" in data:
                    # stable batch format -> v3 single format (exact match only)
                    norm = symbols_str.replace("-", ".")
                    found = None
                    for entry in data["historicalStockList"]:
                        if entry.get("symbol", "").replace("-", ".") == norm:
                            found = {
                                "symbol": entry.get("symbol"),
                                "historical": entry.get("historical", []),
                            }
                            break
                    if found:
                        self._endpoint_failures[base_url] = 0
                        return found
                    valid = False
                    shape_issue = f"'{symbols_str}' not in historicalStockList"
                elif "historical" not in data:
                    valid = False
                    shape_issue = "missing 'historical' key"
                elif is_single and data.get("symbol"):
                    if data["symbol"].replace("-", ".") != symbols_str.replace("-", "."):
                        valid = False
                        shape_issue = (
                            f"response symbol '{data['symbol']}' != requested '{symbols_str}'"
                        )

            if valid:
                self._endpoint_failures[base_url] = 0
                return data
            self._record_endpoint_failure(base_url)
            self._warn_fallback(base_url, is_last, shape_issue or "unexpected response shape")
        return None

    def _warn_fallback(self, base_url: str, is_last: bool, reason: Optional[str]) -> None:
        """Emit a WARN line so users see why a non-last endpoint failed and the
        client is falling back. No-op when the failing endpoint is the last one
        (its error was already printed by _rate_limited_get with quiet=False)."""
        if is_last or not reason:
            return
        print(
            f"WARN: {base_url} failed ({reason}); falling back to next endpoint",
            file=sys.stderr,
        )

    def _record_endpoint_failure(self, base_url: str) -> None:
        """Track consecutive failures and disable endpoint after threshold."""
        failures = self._endpoint_failures.get(base_url, 0) + 1
        self._endpoint_failures[base_url] = failures
        if failures >= self._ENDPOINT_FAILURE_THRESHOLD:
            self._disabled_endpoints.add(base_url)

    def get_earnings_calendar(self, from_date: str, to_date: str) -> Optional[list[dict]]:
        """Fetch earnings calendar for a date range.

        Args:
            from_date: Start date in YYYY-MM-DD format
            to_date: End date in YYYY-MM-DD format

        Returns:
            List of earnings event dicts or None on failure.
            Each dict contains: date, symbol, eps, epsEstimated, revenue,
            revenueEstimated, time (bmo/amc)
        """
        cache_key = f"earnings_{from_date}_{to_date}"
        if cache_key in self.cache:
            return self.cache[cache_key]

        url = "https://financialmodelingprep.com/stable/earnings-calendar"
        data = self._rate_limited_get(url, {"from": from_date, "to": to_date})
        if data:
            self.cache[cache_key] = data
        return data

    def get_company_profiles(self, symbols: list[str]) -> dict[str, dict]:
        """Fetch company profiles for multiple symbols.

        The /stable profile endpoint does not support comma-batched symbols
        (a multi-symbol request returns ``[]``), so fetch one symbol at a time.

        Args:
            symbols: List of stock symbols

        Returns:
            Dict mapping symbol -> profile dict (with marketCap, sector, etc.)
        """
        results = {}
        for symbol in symbols:
            cache_key = f"profile_{symbol}"
            if cache_key in self.cache:
                cached = self.cache[cache_key]
                if isinstance(cached, dict):
                    results[symbol] = cached
                continue

            url = "https://financialmodelingprep.com/stable/profile"
            data = self._rate_limited_get(url, {"symbol": symbol})
            if data and isinstance(data, list) and data:
                profile = data[0]
                if isinstance(profile, dict):
                    # Preserve the prior lenient behavior: a profile that omits
                    # "symbol" is still returned under the requested symbol.
                    self.cache[cache_key] = profile
                    results[profile.get("symbol", symbol)] = profile
        return results

    def get_historical_prices(self, symbol: str, days: int = 90) -> Optional[dict]:
        """Fetch historical daily OHLCV data.

        Args:
            symbol: Stock symbol
            days: Number of trading days to fetch

        Returns:
            Dict with 'symbol' and 'historical' keys, where 'historical' is a
            list of price dicts (most-recent-first) with: date, open, high, low,
            close, adjClose, volume
        """
        cache_key = f"prices_{symbol}_{days}"
        if cache_key in self.cache:
            return self.cache[cache_key]

        data = self._request_with_fallback("historical", symbol, {"timeseries": days})
        if data:
            self.cache[cache_key] = data
        return data

    def get_api_stats(self) -> dict:
        """Return API usage statistics."""
        return {
            "cache_entries": len(self.cache),
            "api_calls_made": self.api_calls_made,
            "max_api_calls": self.max_api_calls,
            "rate_limit_reached": self.rate_limit_reached,
            "budget_remaining": max(0, self.max_api_calls - self.api_calls_made),
        }
