#!/usr/bin/env python3
# GENERATED by scripts/generate_fmp_client.py — do not edit.
# Source of truth: scripts/fmp_client/specials/ and scripts/fmp_client/registry.py.
# Regenerate: python3 scripts/generate_fmp_client.py
"""
FMP API Client for FTD Detector

Provides rate-limited access to Financial Modeling Prep API endpoints.

Features:
- Rate limiting (0.3s between requests)
- Automatic retry on 429 errors
- Session caching for duplicate requests
- Batch quote support
"""

import math
import os
import sys
import time
from datetime import date, timedelta
from pathlib import Path
from typing import Optional

try:
    import requests
except ImportError:
    print("ERROR: requests library not found. Install with: pip install requests", file=sys.stderr)
    sys.exit(1)

SKILL_ROOT = Path(__file__).resolve().parents[3]
if str(SKILL_ROOT) not in sys.path:
    sys.path.insert(0, str(SKILL_ROOT))

try:
    from fmp_compat import fmp_get, get_fmp_keys
except ImportError:  # standalone .skill install without the repo-root module
    fmp_get = None

    def get_fmp_keys():
        return []


# --- FMP endpoint: stable only. FMP retired v3 for non-legacy keys on
# 2025-08-31; a v3 URL requested through fmp_compat is rewritten back to the
# equivalent stable endpoint anyway (see `_V3_TO_STABLE` in the repo-root
# fmp_compat.py), so a second "v3 fallback" entry here was never a distinct
# endpoint — it was a second, rate-limited query of the SAME stable endpoint
# plus a misleading WARN line (WPP-20260827-012). The cross-provider fallback
# is yfinance, wired into the callers below. ---


def _stable_quote_url(base, symbols_str, params):
    """stable/quote?symbol=^GSPC"""
    params["symbol"] = symbols_str
    return base, params


def _stable_hist_url(base, symbols_str, params):
    """stable/historical-price-eod/full?symbol=^GSPC&from=...&to=..."""
    params["symbol"] = symbols_str
    # New stable EOD endpoint ignores `timeseries`; convert to from/to range
    # to bound the payload. Use 2x calendar days to cover N trading days
    # (trading-day/calendar-day ratio ~252/365 ~0.69, so *2 leaves headroom).
    days = params.pop("timeseries", None)
    if days is not None:
        today = date.today()
        params["from"] = (today - timedelta(days=int(days) * 2)).isoformat()
        params["to"] = today.isoformat()
    return base, params


_FMP_ENDPOINTS = {
    "quote": [
        ("https://financialmodelingprep.com/stable/quote", _stable_quote_url),
    ],
    "historical": [
        ("https://financialmodelingprep.com/stable/historical-price-eod/full", _stable_hist_url),
    ],
}


def _normalize_eod_flat_list(data, symbols_str: str, limit: Optional[int] = None):
    """Convert stable/historical-price-eod/full flat list to v3-compatible dict.

    Input  : [{"symbol": "SPY", "date": "...", "open": ..., ...}, ...]
    Output : {"symbol": "SPY", "historical": [{"date": ..., "open": ..., ...}, ...]}

    Returns the input unchanged if not a list (passthrough for the dict /
    historicalStockList shapes the stable batch format can still return).
    Returns None when no row matches the requested symbol; the caller will
    record the failure and try the next endpoint.

    If `limit` is provided (the original `timeseries=N` request), the
    `historical` list is truncated to the first `limit` entries. The new
    EOD endpoint ignores `timeseries` and returns the full available history,
    so the caller's date-range bounding plus this truncation together preserve
    the legacy "most-recent N rows" contract. Truncation assumes descending
    date order, which the FMP EOD endpoint provides (verified live).

    Note: empty list ``[]`` does not reach this normalizer because the caller's
    ``if not data: continue`` falsy check handles it earlier in
    ``_request_with_fallback``.
    """
    if not isinstance(data, list):
        return data
    if not data:
        return None
    norm_target = symbols_str.replace("-", ".")
    matched_symbol = None
    historical = []
    for row in data:
        if not isinstance(row, dict):
            continue
        # Be permissive: single-symbol endpoint may omit per-row "symbol".
        # Treat missing symbol as belonging to the requested symbols_str.
        row_sym = row.get("symbol") or symbols_str
        if row_sym.replace("-", ".") != norm_target:
            continue
        matched_symbol = matched_symbol or row_sym
        historical.append({k: v for k, v in row.items() if k != "symbol"})
    if not historical:
        return None
    if limit is not None and limit > 0:
        historical = historical[:limit]
    return {"symbol": matched_symbol or symbols_str, "historical": historical}


# --- WPP-20260818-009: one validated-bar boundary for every provider ---------
#
# `float(x or 0)` cannot catch NaN — `bool(float("nan")) is True` — so the
# yfinance fallback minted a NaN close on 2026-08-18, and `_normalize_eod_flat_list`
# copies FMP row values verbatim, so the API side can mint one too (`json.loads`
# accepts bare `NaN` by default). Downstream, NaN fails EVERY comparison: in
# `rally_tracker.detect_ftd`, `NaN < FTD_GAIN_MINIMUM` is False, so a bar with no
# close is not rejected — it is declared a Follow-Through Day, which fabricates
# `dual_confirmation` and a 15-point quality component.
#
# The rule, stated once: no missing or non-finite observation may be converted
# into a value that reads as a valid one, and no gap may be closed by making two
# non-adjacent bars adjacent.


def _finite(value) -> bool:
    """True for a real, finite number. `bool` is not a price.

    `math.isfinite` RAISES `OverflowError` on a Python int beyond the float range
    (`10 ** 1000`), so an unguarded call turns malformed data into a crash instead
    of a rejection — the same class the allocator's codex gate caught in
    `math.isfinite(10 ** 400)` on 2026-08-27. A predicate that can raise is not a
    predicate.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return False
    try:
        return math.isfinite(value)
    except OverflowError:
        return False


def _finite_positive(value) -> bool:
    """True for a real, finite, strictly positive number."""
    return _finite(value) and value > 0


def _finite_non_negative(value) -> bool:
    """True for a real, finite, non-negative number (volume may legitimately be 0)."""
    return _finite(value) and value >= 0


_PRICE_FIELDS = ("open", "high", "low", "adjClose")

# How many leading (newest) invalid bars may be trimmed before the payload is
# refused outright. Trimming exists for a session that has not settled yet — one
# bar in the ordinary case, a little slack for a provider that emits placeholder
# rows across a holiday stretch. Beyond that it is an outage, not an unsettled
# bar, and the honest answer is no history rather than a truncated one.
_MAX_LEADING_TRIM = 3

# The shortest series worth returning after a trim — `rally_tracker`'s own floor
# (`analyze_single_index` refuses a history below this length).
_MIN_USABLE_BARS = 10


def _bar_is_valid(bar) -> bool:
    """A bar is an observation iff `close` is a real, positive number and every
    price/volume field it *carries* is one too.

    Deliberately scoped to PRESENT fields. The defect is a non-finite value
    reading as valid, not an incomplete payload: callers already have `.get(key,
    default)` fallbacks for genuinely absent keys, and turning this into a
    completeness requirement would reject legitimate partial responses — work
    this row does not ask for (P6). A key present with `None` is *not* absent:
    `.get("low", fallback)` returns the `None`, which is how a null close
    reached `analyze_single_index` and raised `TypeError`.

    `close > 0` is also what removes the `x / 0` route by which finite inputs
    still produce a non-finite `change_pct` downstream.
    """
    if not isinstance(bar, dict):
        return False
    if not _finite_positive(bar.get("close")):
        return False
    if any(key in bar and not _finite_positive(bar[key]) for key in _PRICE_FIELDS):
        return False
    return "volume" not in bar or _finite_non_negative(bar["volume"])


def _bar_date(bar) -> Optional[date]:
    raw = bar.get("date") if isinstance(bar, dict) else None
    if not isinstance(raw, str):
        return None
    try:
        return date.fromisoformat(raw[:10])
    except ValueError:
        return None


def _validate_history(payload):
    """Return `payload` with a trustworthy `historical`, or None.

    * Trims LEADING invalid bars. `historical` is most-recent-first here, so a
      leading invalid bar is an unsettled newest session; dropping it is
      equivalent to running before that session existed and leaves everything
      older contiguous.
    * REJECTS the whole payload on any invalid bar after the first valid one.
      `rally_tracker` counts rally days by position, so splicing out an interior
      bar compresses day numbering, compares volume across non-adjacent sessions
      and can manufacture an FTD — a silent wrong verdict in place of a loud NaN.
    * REJECTS unless `date` is strictly descending. Trim-leading is only safe in
      that order, and the v3 passthrough shape cannot be proven offline, so the
      assumption is checked rather than assumed.
    * Never repairs a field. Substituting 0.0 for a missing `low` would set
      `ftd_low = 0`, permanently disabling `check_ftd_invalidation` — invisible,
      and strictly worse than the NaN it replaced.
    """
    if not isinstance(payload, dict):
        return None
    bars = payload.get("historical")
    if not isinstance(bars, list) or not bars:
        return None

    first_valid = None
    for i, bar in enumerate(bars):
        if _bar_is_valid(bar):
            first_valid = i
            break
    if first_valid is None:
        return None

    # Trimming is for an UNSETTLED NEWEST SESSION, not for an outage. Without a
    # cap, an 80-row response whose newest 58 rows are invalid would silently
    # become a 22-row stale history that still scores and still labels itself
    # decision-grade (codex gate r2). A run that has lost most of its recent
    # sessions has no business producing a verdict.
    if first_valid > _MAX_LEADING_TRIM:
        return None

    # Order is proven over the WHOLE list, BEFORE anything is trimmed — checking
    # only the surviving tail would let a discarded prefix bar be chronologically
    # INTERIOR: an invalid 2026-08-16 ahead of a valid 08-18 / 08-17 / 08-15
    # leaves a descending remainder while deleting the session between 08-17 and
    # 08-15 (codex gate r1). Descending order is what makes "leading == newest"
    # true, so it must hold before trimming means anything.
    #
    # But it is required only WHERE IT IS LOAD-BEARING. Demanding a `date` on
    # every bar rejected FMP's legitimately minimal v3 shape and broke the
    # symbol-mismatch fallback (codex gate r2). The exception is sound for ONE
    # undated bar and no other count: a single observation asserts no adjacency,
    # whereas two or more undated bars are handed to `rally_tracker` as
    # consecutive trading days, so an oldest-first or gapped payload can produce
    # a false FTD with nothing to detect it (codex gate r3).
    #
    # all bars dated          -> prove strictly descending
    # exactly one bar, undated, untrimmed -> accept, nothing is asserted
    # anything else           -> refuse
    parsed = [_bar_date(bar) for bar in bars]
    dated = [d is not None for d in parsed]
    if all(dated):
        previous = None
        for current in parsed:
            if previous is not None and current >= previous:
                return None
            previous = current
    elif any(dated) or first_valid > 0 or len(bars) > 1:
        return None

    kept = bars[first_valid:]
    if not all(_bar_is_valid(bar) for bar in kept):
        return None

    # A trim must not manufacture a series too short to mean anything.
    # `ftd_detector.main` derives `decision_grade` from truthiness, so a two-bar
    # tail would be labelled decision-grade and its score consumed by
    # exposure-coach at full weight, even though `analyze_single_index` refuses
    # to analyse it (codex gate r3). Applied only WHEN a trim occurred: a natively
    # short payload behaves exactly as it did before this change.
    if first_valid > 0 and len(kept) < _MIN_USABLE_BARS:
        return None

    if first_valid == 0:
        # Validation is a check, not a transform. Returning the caller's own
        # object keeps the pre-existing aliasing (`data["data_source"] = ...`
        # writes through to the response dict) intact for the common path.
        return payload
    validated = dict(payload)
    validated["historical"] = kept
    return validated


def _yf_history(symbol: str, days: int) -> Optional[dict]:
    """Fetch daily OHLCV from yfinance and normalize to FMP historical shape."""
    try:
        import yfinance as yf
    except ImportError:
        return None

    try:
        period_days = max(int(days * 2), 10)
        hist = yf.Ticker(symbol).history(period=f"{period_days}d", auto_adjust=False)
    except Exception:
        return None

    if hist is None or hist.empty:
        return None

    # Construction must not be able to raise on any cell value: `int(NaN)` raises
    # ValueError, and this loop runs newest-first, so the old `int(x or 0)` would
    # have blown up on iteration 1 for the exact unsettled-latest-bar shape that
    # trim-leading exists to salvage. Volume is carried as a float and int-cast
    # only after `_validate_history` has judged the bar. Nothing is defaulted:
    # judging validity belongs to the boundary, repairing a field belongs nowhere.
    def _cell(row, key, fallback_key=None):
        value = row.get(key)
        if value is None and fallback_key is not None:
            value = row.get(fallback_key)
        try:
            return float(value)
        except (TypeError, ValueError, OverflowError):
            return None

    rows = []
    for idx, row in hist.tail(days).iloc[::-1].iterrows():
        rows.append(
            {
                "date": idx.date().isoformat(),
                "open": _cell(row, "Open"),
                "high": _cell(row, "High"),
                "low": _cell(row, "Low"),
                "close": _cell(row, "Close"),
                "adjClose": _cell(row, "Adj Close", "Close"),
                "volume": _cell(row, "Volume"),
            }
        )
    if not rows:
        return None
    return {"symbol": symbol, "historical": rows, "data_source": "yfinance"}


def _yf_quote(symbol: str) -> Optional[dict]:
    """Fetch a quote-like record from yfinance."""
    hist = _yf_history(symbol, 5)
    if not hist or not hist.get("historical"):
        return None
    latest = hist["historical"][0]
    # The NEWEST RAW bar, deliberately — not the newest surviving one. Reporting
    # a prior session's close under a `quote` provenance label would make the
    # artifact's own source field assert something untrue. Returning None routes
    # the caller into its documented "using historical close as current price"
    # branch, which labels the number honestly.
    if not _bar_is_valid(latest):
        return None
    prev = hist["historical"][1] if len(hist["historical"]) > 1 else latest
    price = latest["close"]
    prev_price = prev.get("close") if _bar_is_valid(prev) else price
    change = price - prev_price
    change_pct = (change / prev_price * 100) if prev_price else 0
    return {
        "symbol": symbol,
        "price": price,
        "change": change,
        "changePercentage": change_pct,
        "volume": latest.get("volume", 0),
        "data_source": "yfinance",
    }


class FMPClient:
    """Client for Financial Modeling Prep API with rate limiting and caching"""

    BASE_URL = "https://financialmodelingprep.com/api/v3"
    RATE_LIMIT_DELAY = 0.3  # 300ms between requests

    _ENDPOINT_FAILURE_THRESHOLD = 3  # disable endpoint after N consecutive failures

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("FMP_API_KEY")
        # In standalone yf-only mode (fmp_get is None) no FMP call can ever be
        # made, so a missing key must not abort construction — this ValueError
        # was the SECOND way a bare .skill install died before reaching the
        # yfinance fallback (WPP-20260831-001 corollary).
        if not self.api_key and fmp_get is not None:
            raise ValueError(
                "FMP API key required. Set FMP_API_KEY environment variable "
                "or pass api_key parameter."
            )
        self.session = requests.Session()
        if self.api_key:
            self.session.headers.update({"apikey": self.api_key})
        self.cache = {}
        self.last_call_time = 0
        self.rate_limit_reached = False
        self.retry_count = 0
        self.max_retries = 1
        self.api_calls_made = 0
        # Circuit breaker: track consecutive failures per endpoint URL prefix
        self._endpoint_failures: dict[str, int] = {}
        self._disabled_endpoints: set[str] = set()
        self.data_sources: dict[str, str] = {}
        # Most recent transport-level failure reason; set by _rate_limited_get
        # so _request_with_fallback can surface suppressed errors even when
        # an endpoint was called with quiet=True.
        self._last_error: Optional[str] = None

    def _rate_limited_get(
        self, url: str, params: Optional[dict] = None, quiet: bool = False
    ) -> Optional[dict]:
        self._last_error = None
        if self.rate_limit_reached:
            self._last_error = "daily rate limit already reached"
            return None

        if params is None:
            params = {}

        elapsed = time.time() - self.last_call_time
        if elapsed < self.RATE_LIMIT_DELAY:
            time.sleep(self.RATE_LIMIT_DELAY - elapsed)

        if fmp_get is None:
            # Standalone .skill install: the repo-root fmp_compat transport is
            # absent, so FMP is typed-unavailable and the yfinance fallback is
            # the only provider. WARN once, then quietly return misses.
            if not getattr(self, "_warned_no_fmp_compat", False):
                print(
                    "WARNING: fmp_compat unavailable (standalone install) — "
                    "FMP disabled, running yfinance-only",
                    file=sys.stderr,
                )
                self._warned_no_fmp_compat = True
            self._last_error = "fmp_compat unavailable (standalone install)"
            return None

        data = fmp_get(url, params=params, timeout=30, max_retries_per_key=1)
        self.last_call_time = time.time()
        self.api_calls_made += 1
        if data is None:
            if not get_fmp_keys():
                self._last_error = "FMP keys not in environment"
                if not quiet:
                    print(
                        "ERROR: FMP keys not in environment — likely a source/export bug, not a quota issue",
                        file=sys.stderr,
                    )
            else:
                self._last_error = "fmp_get failed or quota-limited (429/402/whitelist)"
                if not quiet:
                    print(f"ERROR: FMP request failed or quota-limited: {url}", file=sys.stderr)
        return data

    def _request_with_fallback(self, endpoint_key, symbols_str, extra_params=None):
        """Query the stable FMP endpoint; the loop shape stays even though the
        endpoint list is now a single entry (WPP-20260827-012 — stable is the
        only FMP endpoint; through fmp_compat, a v3 URL was rewritten back to
        stable anyway, so a second v3 leg here would just be a second,
        rate-limited query of the same endpoint). The cross-provider fallback
        is yfinance, wired into the callers below.

        Returns parsed JSON in the historical/quote shape callers expect, or
        None if the endpoint fails.
        """
        params = dict(extra_params) if extra_params else {}
        endpoints = _FMP_ENDPOINTS[endpoint_key]
        is_single = "," not in symbols_str

        for i, (base_url, url_builder) in enumerate(endpoints):
            # Circuit breaker: skip endpoints with too many consecutive failures
            if base_url in self._disabled_endpoints:
                continue

            url, final_params = url_builder(base_url, symbols_str, dict(params))
            is_last = i == len(endpoints) - 1
            data = self._rate_limited_get(url, final_params, quiet=not is_last)
            if not data:  # falsy (None, [], {}) — try next endpoint
                self._record_endpoint_failure(base_url)
                self._warn_fallback(base_url, is_last, self._last_error)
                continue

            # Normalize new stable EOD flat-list shape to v3-compatible dict.
            # No-op for v3 dict / historicalStockList responses.
            # `timeseries` (original request) is passed as `limit` so the
            # EOD endpoint's full-history response is truncated to the
            # legacy "most-recent N rows" contract.
            if endpoint_key == "historical":
                limit = params.get("timeseries") if isinstance(params, dict) else None
                data = _normalize_eod_flat_list(data, symbols_str, limit=limit)
                if not data:
                    self._record_endpoint_failure(base_url)
                    self._warn_fallback(
                        base_url,
                        is_last,
                        f"response had no rows matching '{symbols_str}'",
                    )
                    continue

            # Shape validation: reject truthy-but-wrong-shape responses
            valid = True
            shape_issue: Optional[str] = None
            if endpoint_key == "quote":
                if not isinstance(data, list) or len(data) == 0:
                    valid = False
                    shape_issue = "expected non-empty list"
                elif is_single and not any(
                    q.get("symbol", "").replace("-", ".") == symbols_str.replace("-", ".")
                    for q in data
                ):
                    valid = False
                    shape_issue = f"requested symbol '{symbols_str}' not in response"

            if endpoint_key == "historical":
                if not isinstance(data, dict):
                    valid = False
                    shape_issue = "expected dict"
                elif "historicalStockList" in data:
                    # stable batch format -> v3 single format (exact match only)
                    norm = symbols_str.replace("-", ".")
                    found = None
                    for entry in data["historicalStockList"]:
                        if entry.get("symbol", "").replace("-", ".") == norm:
                            found = {
                                "symbol": entry.get("symbol"),
                                "historical": entry.get("historical", []),
                            }
                            break
                    if found:
                        validated = _validate_history(found)
                        if validated:
                            self._endpoint_failures[base_url] = 0
                            return validated
                        self._record_endpoint_failure(base_url)
                        self._warn_fallback(
                            base_url, is_last, "no trustworthy bars in historicalStockList entry"
                        )
                        continue
                    valid = False
                    shape_issue = f"'{symbols_str}' not in historicalStockList"
                elif "historical" not in data:
                    valid = False
                    shape_issue = "missing 'historical' key"
                elif is_single and data.get("symbol"):
                    if data["symbol"].replace("-", ".") != symbols_str.replace("-", "."):
                        valid = False
                        shape_issue = (
                            f"response symbol '{data['symbol']}' != requested '{symbols_str}'"
                        )

            # Content validation runs HERE, inside the endpoint loop — not in the
            # public wrapper. A stable response that is shape-valid but carries a
            # non-finite or out-of-order bar is a FAILED ENDPOINT that must be
            # recorded as one (`_record_endpoint_failure`/`_warn_fallback` below);
            # validating one level up skipped straight to yfinance without ever
            # marking the endpoint failed, which broke the disable-after-N-failures
            # circuit breaker (codex gate r1).
            if valid:
                if endpoint_key == "historical":
                    validated = _validate_history(data)
                    if not validated:
                        valid = False
                        shape_issue = "no trustworthy bars (non-finite or out-of-order)"
                    else:
                        data = validated
                elif endpoint_key == "quote":
                    candidates = [q for q in data if isinstance(q, dict)]
                    if is_single:
                        # Identity before price. The shape check above only proves
                        # the requested symbol is PRESENT; filtering on price alone
                        # could drop that row and leave an unrelated one, handing
                        # `ftd_detector` a different security as its quote
                        # (codex gate r3). Narrow to the requested symbol first, so
                        # an invalid price fails the endpoint rather than
                        # substituting a neighbour.
                        norm = symbols_str.replace("-", ".")
                        candidates = [
                            q
                            for q in candidates
                            if (q.get("symbol") or symbols_str).replace("-", ".") == norm
                        ]
                    kept_quotes = [q for q in candidates if _finite_positive(q.get("price"))]
                    if not kept_quotes:
                        valid = False
                        shape_issue = "no quote carried a real, positive price"
                    else:
                        data = kept_quotes

            if valid:
                self._endpoint_failures[base_url] = 0
                return data
            self._record_endpoint_failure(base_url)
            self._warn_fallback(base_url, is_last, shape_issue or "unexpected response shape")
        return None

    def _warn_fallback(self, base_url: str, is_last: bool, reason: Optional[str]) -> None:
        """Emit a WARN line so users see why a non-last endpoint failed and the
        client is falling back. No-op when the failing endpoint is the last one
        (its error was already printed by _rate_limited_get with quiet=False)."""
        if is_last or not reason:
            return
        print(
            f"WARN: {base_url} failed ({reason}); falling back to next endpoint",
            file=sys.stderr,
        )

    def _record_endpoint_failure(self, base_url: str) -> None:
        """Track consecutive failures and disable endpoint after threshold."""
        failures = self._endpoint_failures.get(base_url, 0) + 1
        self._endpoint_failures[base_url] = failures
        if (
            failures >= self._ENDPOINT_FAILURE_THRESHOLD
            and base_url not in self._disabled_endpoints
        ):
            self._disabled_endpoints.add(base_url)
            print(
                f"WARNING: FMP endpoint disabled for the rest of this run after "
                f"{failures} consecutive failures: {base_url}",
                file=sys.stderr,
            )

    def get_quote(self, symbols: str) -> Optional[list[dict]]:
        """Fetch real-time quote data for one or more symbols (comma-separated)"""
        cache_key = f"quote_{symbols}"
        if cache_key in self.cache:
            return self.cache[cache_key]

        # FMP-side price validation lives in `_request_with_fallback` so a bad
        # stable response is recorded as a failed endpoint before this method
        # ever sees it, rather than silently skipping to yfinance.
        data = self._request_with_fallback("quote", symbols)
        if not data:
            quotes = []
            for symbol in symbols.split(","):
                quote = _yf_quote(symbol)
                if quote and _finite_positive(quote.get("price")):
                    quotes.append(quote)
                    self.data_sources[f"quote:{symbol}"] = "yfinance"
            data = quotes or None
        else:
            for quote in data:
                self.data_sources[f"quote:{quote.get('symbol', symbols)}"] = "fmp"
        if data:
            self.cache[cache_key] = data
        return data

    def get_historical_prices(self, symbol: str, days: int = 365) -> Optional[dict]:
        """Fetch historical daily OHLCV data"""
        cache_key = f"prices_{symbol}_{days}"
        if cache_key in self.cache:
            return self.cache[cache_key]

        # The FMP endpoint validates inside `_request_with_fallback`; the
        # yfinance fallback below has no such loop, so it is validated here.
        # Both go through the SAME predicate,
        # and in both cases validation precedes the provenance stamp and the cache
        # write — a rejected payload must not claim a source it could not supply,
        # and must not be cached, or every later caller (`get_batch_historical`
        # included) is re-served the same poison from memory.
        data = self._request_with_fallback("historical", symbol, {"timeseries": days})
        if not data:
            data = _validate_history(_yf_history(symbol, days))
            if data:
                # `_yf_history` carries volume as a float so construction cannot
                # raise on a NaN cell; restore the integral shape now that the
                # bar has been judged. FMP payloads are left byte-untouched.
                data["historical"] = [
                    {**bar, "volume": int(bar["volume"])}
                    if _finite_non_negative(bar.get("volume"))
                    else bar
                    for bar in data["historical"]
                ]
                data["data_source"] = "yfinance"
                self.data_sources[f"historical:{symbol}"] = "yfinance"
        else:
            data["data_source"] = data.get("data_source", "fmp")
            self.data_sources[f"historical:{symbol}"] = data["data_source"]
        if data:
            self.cache[cache_key] = data
        return data

    def get_batch_quotes(self, symbols: list[str]) -> dict[str, dict]:
        """Fetch quotes for a list of symbols, batching up to 5 per request"""
        results = {}
        batch_size = 5
        for i in range(0, len(symbols), batch_size):
            batch = symbols[i : i + batch_size]
            batch_str = ",".join(batch)
            quotes = self.get_quote(batch_str)
            if quotes:
                for q in quotes:
                    results[q["symbol"]] = q
        return results

    def get_batch_historical(self, symbols: list[str], days: int = 50) -> dict[str, list[dict]]:
        """Fetch historical prices for multiple symbols"""
        results = {}
        for symbol in symbols:
            data = self.get_historical_prices(symbol, days=days)
            if data and "historical" in data:
                results[symbol] = data["historical"]
        return results

    def calculate_sma(self, prices: list[float], period: int) -> float:
        """Calculate Simple Moving Average from a list of prices (most recent first)"""
        if len(prices) < period:
            return sum(prices) / len(prices)
        return sum(prices[:period]) / period

    def calculate_ema(self, prices: list[float], period: int) -> float:
        """Calculate Exponential Moving Average from a list of prices (most recent first)"""
        if len(prices) < period:
            return sum(prices) / len(prices)

        prices_reversed = prices[::-1]
        sma = sum(prices_reversed[:period]) / period
        ema = sma
        k = 2 / (period + 1)
        for price in prices_reversed[period:]:
            ema = price * k + ema * (1 - k)
        return ema

    def get_api_stats(self) -> dict:
        """Return API usage statistics."""
        return {
            "cache_entries": len(self.cache),
            "api_calls_made": self.api_calls_made,
            "rate_limit_reached": self.rate_limit_reached,
            "data_sources": self.data_sources,
        }
