#!/usr/bin/env python3
# GENERATED by scripts/generate_fmp_client.py — do not edit.
# Source of truth: scripts/fmp_client/specials/ and scripts/fmp_client/registry.py.
# Regenerate: python3 scripts/generate_fmp_client.py
"""
FMP API Client for CANSLIM Screener

Provides rate-limited access to Financial Modeling Prep API endpoints
required for CANSLIM component analysis (C, A, N, M).

Features:
- Rate limiting (0.3s between requests)
- Automatic retry on 429 errors
- Session caching for duplicate requests
- Error handling and logging
"""

import os
import sys
import time
from datetime import date, timedelta
from pathlib import Path
from typing import Optional

try:
    import requests
except ImportError:
    print("ERROR: requests library not found. Install with: pip install requests", file=sys.stderr)
    sys.exit(1)

SKILL_ROOT = Path(__file__).resolve().parents[3]
if str(SKILL_ROOT) not in sys.path:
    sys.path.insert(0, str(SKILL_ROOT))

try:
    from fmp_compat import fmp_get_typed, key_override, request_count
except ImportError:  # standalone .skill install without the repo-root module
    fmp_get_typed = None


# --- FMP endpoint: stable only. FMP retired v3 for non-legacy keys on
# 2025-08-31; a v3 URL requested through fmp_compat is rewritten back to the
# equivalent stable endpoint anyway, so a second "v3 fallback" entry here was
# never a distinct endpoint (WPP-20260827-012). ---


def _stable_quote_url(base, symbols_str, params):
    """stable/quote?symbol=^GSPC"""
    params["symbol"] = symbols_str
    return base, params


def _stable_hist_url(base, symbols_str, params):
    """stable/historical-price-eod/full?symbol=^GSPC&timeseries=80

    `timeseries` is passed through unchanged — fmp_compat's own
    `_prepare_params_for_url` converts it into a from/to range plus an
    internal `_tm_limit` truncation bound before the request is made.
    """
    params["symbol"] = symbols_str
    return base, params


_FMP_ENDPOINTS = {
    "quote": [
        ("https://financialmodelingprep.com/stable/quote", _stable_quote_url),
    ],
    "historical": [
        ("https://financialmodelingprep.com/stable/historical-price-eod/full", _stable_hist_url),
    ],
}


class FMPClient:
    """Client for Financial Modeling Prep API with rate limiting and caching"""

    BASE_URL = "https://financialmodelingprep.com/stable"
    STABLE_URL = "https://financialmodelingprep.com/stable"
    RATE_LIMIT_DELAY = 0.3  # 300ms between requests (200 requests/minute max)

    def __init__(self, api_key: Optional[str] = None):
        """
        Initialize FMP API client

        Args:
            api_key: FMP API key (defaults to FMP_API_KEY environment variable)

        Raises:
            ValueError: If API key not provided and not in environment
        """
        self.api_key = api_key or os.getenv("FMP_API_KEY")
        if not self.api_key:
            raise ValueError(
                "FMP API key required. Set FMP_API_KEY environment variable "
                "or pass api_key parameter."
            )

        self.cache = {}  # Simple in-memory cache for session
        self.last_call_time = 0
        self.rate_limit_reached = False
        self.retry_count = 0
        self.max_retries = 1
        self.api_calls_made = 0
        # Circuit breaker: track consecutive failures per endpoint URL prefix
        self._endpoint_failures: dict[str, int] = {}
        self._disabled_endpoints: set[str] = set()
        self._ENDPOINT_FAILURE_THRESHOLD = 3
        self._last_error: Optional[str] = None

    def _raw_stable_get(self, url: str, params: dict) -> Optional[dict]:
        """Thin standalone fallback when fmp_compat is not importable — a
        `.skill` archive bundles this file but not the repo-root
        `fmp_compat.py`. One request, no key failover, no v3 rung."""
        try:
            response = requests.get(url, params=self._raw_params(url, params), timeout=30)
            if response.status_code == 200:
                return self._raw_fold(url, params, response.json())
            if response.status_code == 429:
                # No second key on this path: an exhausted quota must stop
                # the run instead of burning every later symbol against it
                # (codex nested gate r2 P1).
                self.rate_limit_reached = True
                self._last_error = "HTTP 429 (daily rate limit) — standalone, no failover"
                return None
            self._last_error = f"HTTP {response.status_code} — standalone, no failover"
            return None
        except (requests.exceptions.RequestException, ValueError) as exc:
            self._last_error = f"standalone request failed: {type(exc).__name__}"
        return None

    def _raw_params(self, url: str, params: dict) -> dict:
        """Standalone path only: the stable EOD endpoint ignores `timeseries`,
        so bound the payload with a from/to range the way fmp_compat's
        `_prepare_params_for_url` does (2x calendar days covers N trading
        days); the row truncation happens in `_raw_fold`."""
        prepared = {k: v for k, v in params.items() if k != "timeseries"}
        if "historical-price-eod/full" in url and "timeseries" in params:
            today = date.today()
            prepared["from"] = (today - timedelta(days=int(params["timeseries"]) * 2)).isoformat()
            prepared["to"] = today.isoformat()
        prepared["apikey"] = self.api_key
        return prepared

    def _raw_fold(self, url: str, params: dict, data):
        """Standalone path only: fold the stable EOD flat list into the
        `{"symbol", "historical": [...]}` shape `_request_with_fallback`
        validates (fmp_compat does this on the shared path). Fail CLOSED on a
        malformed row — a shortened series that still looks complete is
        laundered evidence (WPP-20260902-002). Non-EOD payloads and the
        `historicalStockList` dict pass through unchanged (codex nested gate
        r1 P1, 2026-09-06)."""
        if "historical-price-eod/full" not in url or not isinstance(data, list):
            return data
        symbol = str(params.get("symbol", ""))
        norm = symbol.replace("-", ".")
        rows = []
        for row in data:
            if not isinstance(row, dict) or "date" not in row:
                self._last_error = "malformed EOD row in standalone payload — refusing the series"
                return None
            row_symbol = row.get("symbol") or symbol
            if row_symbol.replace("-", ".") != norm:
                continue
            rows.append({k: v for k, v in row.items() if k != "symbol"})
        limit = params.get("timeseries")
        if limit is not None and int(limit) > 0:
            rows = rows[: int(limit)]
        return {"symbol": symbol, "historical": rows}

    def _rate_limited_get(
        self, url: str, params: Optional[dict] = None, quiet: bool = False
    ) -> Optional[dict]:
        """
        Make a rate-limited GET request, delegating transport (key failover,
        retries) to the repo-root fmp_compat module.

        Args:
            url: Full endpoint URL
            params: Query parameters
            quiet: If True, suppress non-fatal error messages (used by fallback)

        Returns:
            JSON response dict, or None on error
        """
        self._last_error = None
        if self.rate_limit_reached:
            self._last_error = "daily rate limit already reached"
            return None

        if params is None:
            params = {}

        elapsed = time.time() - self.last_call_time
        if elapsed < self.RATE_LIMIT_DELAY:
            time.sleep(self.RATE_LIMIT_DELAY - elapsed)

        if fmp_get_typed is None:
            if not getattr(self, "_warned_no_fmp_compat", False):
                print(
                    "WARNING: fmp_compat unavailable (standalone install) — "
                    "using a single stable GET with no key failover",
                    file=sys.stderr,
                )
                self._warned_no_fmp_compat = True
            self.last_call_time = time.time()
            self.api_calls_made += 1
            return self._raw_stable_get(url, params)

        override = self.api_key if self.api_key != os.environ.get("FMP_API_KEY") else None
        before = request_count()
        with key_override(override):
            data, reason = fmp_get_typed(url, params=params, timeout=30, max_retries_per_key=1)
        self.last_call_time = time.time()
        # Every HTTP attempt (retries + key failover) counts (codex nested gate r2 P2).
        self.api_calls_made += max(1, request_count() - before)
        self._last_error = reason
        if data is None:
            if reason == "rate_limited:429":
                self.rate_limit_reached = True
            if not quiet:
                print(f"ERROR: {url} failed ({reason})", file=sys.stderr)
        return data

    def _request_with_fallback(self, endpoint_key, symbols_str, extra_params=None):
        """Query the stable FMP endpoint; the loop shape stays even though the
        endpoint list is now a single entry (WPP-20260827-012 — a v3 URL
        requested through fmp_compat is rewritten back to the same stable
        endpoint anyway, so a second rung was never a distinct endpoint)."""
        params = dict(extra_params) if extra_params else {}
        if endpoint_key == "quote" and "," in symbols_str:
            # /stable/quote serves ONE symbol per request (a comma list
            # returns nothing — verified live 2026-09-06); fan a legacy
            # comma-separated call out per symbol and merge (codex nested
            # gate r2 P2). Stops at the breaker like any other loop.
            merged: list = []
            for one in symbols_str.split(","):
                one = one.strip()
                if not one:
                    continue
                rows = self._request_with_fallback("quote", one, extra_params)
                if rows:
                    merged.extend(rows)
                if self.rate_limit_reached:
                    break
            return merged or None
        endpoints = _FMP_ENDPOINTS[endpoint_key]
        is_single = "," not in symbols_str

        for i, (base_url, url_builder) in enumerate(endpoints):
            if base_url in self._disabled_endpoints:
                continue

            url, final_params = url_builder(base_url, symbols_str, dict(params))
            is_last = i == len(endpoints) - 1
            data = self._rate_limited_get(url, final_params, quiet=not is_last)
            if not data:
                self._record_endpoint_failure(base_url)
                continue

            valid = True
            if endpoint_key == "quote":
                if not isinstance(data, list) or len(data) == 0:
                    valid = False
                elif is_single and not any(
                    q.get("symbol", "").replace("-", ".") == symbols_str.replace("-", ".")
                    for q in data
                ):
                    valid = False

            if endpoint_key == "historical":
                if not isinstance(data, dict):
                    valid = False
                elif "historicalStockList" in data:
                    norm = symbols_str.replace("-", ".")
                    found = None
                    for entry in data["historicalStockList"]:
                        if entry.get("symbol", "").replace("-", ".") == norm:
                            found = {
                                "symbol": entry.get("symbol"),
                                "historical": entry.get("historical", []),
                            }
                            break
                    if found:
                        self._endpoint_failures[base_url] = 0
                        return found
                    valid = False
                elif "historical" not in data:
                    valid = False
                elif is_single and data.get("symbol"):
                    if data["symbol"].replace("-", ".") != symbols_str.replace("-", "."):
                        valid = False

            if valid:
                self._endpoint_failures[base_url] = 0
                return data
            self._record_endpoint_failure(base_url)
        return None

    def _record_endpoint_failure(self, base_url: str) -> None:
        failures = self._endpoint_failures.get(base_url, 0) + 1
        self._endpoint_failures[base_url] = failures
        if failures >= self._ENDPOINT_FAILURE_THRESHOLD:
            self._disabled_endpoints.add(base_url)

    def get_income_statement(
        self, symbol: str, period: str = "quarter", limit: int = 8
    ) -> Optional[list[dict]]:
        """
        Fetch income statement data (quarterly or annual)

        Args:
            symbol: Stock ticker (e.g., "AAPL")
            period: "quarter" or "annual"
            limit: Number of periods to fetch (default 8 for quarterly, 5 for annual)

        Returns:
            List of income statement records (most recent first), or None on error

        Example:
            quarterly = client.get_income_statement("AAPL", period="quarter", limit=8)
            # Returns last 8 quarters (2 years) for YoY comparison
        """
        cache_key = f"income_{symbol}_{period}_{limit}"

        if cache_key in self.cache:
            return self.cache[cache_key]

        params = {"period": period, "limit": limit}
        data = self._rate_limited_get(
            f"{self.STABLE_URL}/income-statement", {**params, "symbol": symbol}
        )

        if data:
            self.cache[cache_key] = data

        return data

    def get_quote(self, symbols: str) -> Optional[list[dict]]:
        """
        Fetch real-time quote data

        Args:
            symbols: Single ticker or comma-separated list (e.g., "AAPL" or "AAPL,MSFT,GOOGL")

        Returns:
            List of quote records, or None on error

        Example:
            quote = client.get_quote("AAPL")
            # Returns [{"symbol": "AAPL", "price": 185.92, "yearHigh": 198.23, ...}]

            quotes = client.get_quote("^GSPC,^VIX")
            # Batch fetch S&P 500 and VIX
        """
        cache_key = f"quote_{symbols}"

        if cache_key in self.cache:
            return self.cache[cache_key]

        data = self._request_with_fallback("quote", symbols)

        if data:
            self.cache[cache_key] = data

        return data

    def get_historical_prices(self, symbol: str, days: int = 365) -> Optional[dict]:
        """
        Fetch historical daily price data

        Args:
            symbol: Stock ticker (e.g., "AAPL")
            days: Number of days of history to fetch (default 365 for 52-week analysis)

        Returns:
            Dict with 'symbol' and 'historical' (list of daily OHLCV records), or None

        Example:
            prices = client.get_historical_prices("AAPL", days=365)
            # prices['historical'][0] = most recent day
            # prices['historical'][251] = 252 trading days ago (~1 year)
        """
        cache_key = f"prices_{symbol}_{days}"

        if cache_key in self.cache:
            return self.cache[cache_key]

        data = self._request_with_fallback("historical", symbol, {"timeseries": days})

        if data:
            self.cache[cache_key] = data

        return data

    def get_profile(self, symbol: str) -> Optional[list[dict]]:
        """
        Fetch company profile (sector, industry, description)

        Args:
            symbol: Stock ticker

        Returns:
            List with single profile dict, or None on error

        Example:
            profile = client.get_profile("AAPL")
            # profile[0] = {"symbol": "AAPL", "companyName": "Apple Inc.", "sector": "Technology", ...}
        """
        cache_key = f"profile_{symbol}"

        if cache_key in self.cache:
            return self.cache[cache_key]

        data = self._rate_limited_get(f"{self.STABLE_URL}/profile", {"symbol": symbol})

        if data:
            # /stable/profile renamed mktCap -> marketCap; expose mktCap so the
            # screener (profile[0]["mktCap"]) keeps working on either endpoint.
            for p in data:
                if isinstance(p, dict) and "mktCap" not in p and "marketCap" in p:
                    p["mktCap"] = p["marketCap"]
            self.cache[cache_key] = data

        return data

    @staticmethod
    def _recent_13f_quarters(as_of=None, count: int = 4):
        """Yield the most recent completed (year, quarter) 13F periods, newest first.

        13F filings lag the quarter end by ~45 days, so the just-completed
        quarter may not be filed yet; the caller walks back until data exists.
        """
        d = as_of or date.today()
        year = d.year
        quarter = (d.month - 1) // 3  # current quarter (1-4) minus 1 = last completed
        if quarter == 0:
            quarter, year = 4, year - 1
        for _ in range(count):
            yield year, quarter
            quarter -= 1
            if quarter == 0:
                quarter, year = 4, year - 1

    def get_institutional_holders(self, symbol: str) -> Optional[dict]:
        """Fetch institutional sponsorship summary (CANSLIM 'I' component).

        Returns a dict::

            {"num_holders": int, "ownership_pct": float | None,
             "top_holders": [{"holder": str, "shares": int, "change": int}, ...]}

        /stable has no single endpoint returning the full holder list (the
        per-holder endpoint is paginated 10/page). Instead this uses
        institutional-ownership/symbol-positions-summary for the holder count
        (investorsHolding) and ownership % (ownershipPercent) — more accurate
        than summing a list — plus extract-analytics/holder (page 0) for the
        top names used in superinvestor detection. Returns None on failure.
        """
        cache_key = f"institutional_{symbol}"
        if cache_key in self.cache:
            return self.cache[cache_key]

        result = None
        # --- /stable: latest available 13F quarter ---
        for year, quarter in self._recent_13f_quarters():
            qp = {"symbol": symbol, "year": year, "quarter": quarter}
            summary = self._rate_limited_get(
                f"{self.STABLE_URL}/institutional-ownership/symbol-positions-summary",
                qp,
                quiet=True,
            )
            if isinstance(summary, list) and summary:
                top = self._rate_limited_get(
                    f"{self.STABLE_URL}/institutional-ownership/extract-analytics/holder",
                    {**qp, "page": 0},
                    quiet=True,
                )
                top_holders = [
                    {
                        "holder": h.get("investorName"),
                        "shares": h.get("sharesNumber"),
                        "change": h.get("changeInSharesNumber"),
                    }
                    for h in (top or [])
                    if isinstance(h, dict)
                ]
                result = {
                    "num_holders": summary[0].get("investorsHolding"),
                    "ownership_pct": summary[0].get("ownershipPercent"),
                    "top_holders": top_holders,
                }
                break

        if result is not None:
            self.cache[cache_key] = result
        return result

    def calculate_ema(self, prices: list[float], period: int = 50) -> float:
        """
        Calculate Exponential Moving Average

        Args:
            prices: List of prices (most recent first)
            period: EMA period (default 50)

        Returns:
            EMA value

        Note:
            This is a helper method for market direction (M component).
            Uses standard EMA formula: EMA = Price * k + EMA_prev * (1-k)
            where k = 2 / (period + 1)
        """
        if len(prices) < period:
            return sum(prices) / len(prices)  # Fallback to simple average

        # Reverse to oldest-first for calculation
        prices_reversed = prices[::-1]

        # Initialize with SMA
        sma = sum(prices_reversed[:period]) / period
        ema = sma

        # Calculate EMA
        k = 2 / (period + 1)
        for price in prices_reversed[period:]:
            ema = price * k + ema * (1 - k)

        return ema

    def clear_cache(self):
        """Clear session cache (useful for refreshing data)"""
        self.cache = {}
        print("Cache cleared", file=sys.stderr)

    def get_api_stats(self) -> dict:
        """
        Get API usage statistics for current session

        Returns:
            Dict with cache size and estimated API calls made
        """
        return {
            "cache_entries": len(self.cache),
            "rate_limit_reached": self.rate_limit_reached,
            "retry_count": self.retry_count,
        }


def test_client():
    """Test FMP client with sample queries"""
    print("Testing FMP Client...")

    client = FMPClient()

    # Test 1: Quote
    print("\n1. Testing quote endpoint (AAPL)...")
    quote = client.get_quote("AAPL")
    if quote:
        print(f"✓ Quote: {quote[0]['symbol']} @ ${quote[0]['price']:.2f}")
    else:
        print("✗ Quote failed")

    # Test 2: Quarterly income statement
    print("\n2. Testing quarterly income statement (AAPL)...")
    quarterly = client.get_income_statement("AAPL", period="quarter", limit=8)
    if quarterly:
        latest = quarterly[0]
        print(f"✓ Latest quarter: {latest['date']}, EPS: ${latest.get('eps', 'N/A')}")
    else:
        print("✗ Quarterly income statement failed")

    # Test 3: Annual income statement
    print("\n3. Testing annual income statement (AAPL)...")
    annual = client.get_income_statement("AAPL", period="annual", limit=5)
    if annual:
        latest = annual[0]
        print(f"✓ Latest year: {latest['date']}, EPS: ${latest.get('eps', 'N/A')}")
    else:
        print("✗ Annual income statement failed")

    # Test 4: Historical prices
    print("\n4. Testing historical prices (AAPL)...")
    prices = client.get_historical_prices("AAPL", days=365)
    if prices and "historical" in prices:
        print(f"✓ Fetched {len(prices['historical'])} days of price history")
        if len(prices["historical"]) > 0:
            latest = prices["historical"][0]
            print(f"  Latest: {latest['date']}, Close: ${latest['close']:.2f}")
    else:
        print("✗ Historical prices failed")

    # Test 5: Market indices (batch)
    print("\n5. Testing market indices (^GSPC, ^VIX)...")
    indices = client.get_quote("^GSPC,^VIX")
    if indices:
        for idx in indices:
            print(f"✓ {idx['symbol']}: {idx['price']:.2f}")
    else:
        print("✗ Market indices failed")

    # Test 6: Cache
    print("\n6. Testing cache (repeat AAPL quote)...")
    quote2 = client.get_quote("AAPL")
    if quote2:
        print("✓ Cache working (no API call made)")

    # Stats
    stats = client.get_api_stats()
    print("\nAPI Stats:")
    print(f"  Cache entries: {stats['cache_entries']}")
    print(f"  Rate limit reached: {stats['rate_limit_reached']}")

    print("\n✓ All tests completed")


if __name__ == "__main__":
    test_client()
