#!/usr/bin/env python3
# GENERATED by scripts/generate_fmp_client.py — do not edit.
# Source of truth: scripts/fmp_client/specials/ and scripts/fmp_client/registry.py.
# Regenerate: python3 scripts/generate_fmp_client.py
"""
FMP API Client for Market Top Detector

Provides rate-limited access to Financial Modeling Prep API endpoints
for market top detection analysis.

Features:
- Rate limiting (0.3s between requests)
- Automatic retry on 429 errors
- Session caching for duplicate requests
- Batch quote support for ETF baskets
"""

import math
import os
import sys
import time
from datetime import date, timedelta
from pathlib import Path
from typing import Optional

try:
    import requests
except ImportError:
    print("ERROR: requests library not found. Install with: pip install requests", file=sys.stderr)
    sys.exit(1)

SKILL_ROOT = Path(__file__).resolve().parents[3]
if str(SKILL_ROOT) not in sys.path:
    sys.path.insert(0, str(SKILL_ROOT))

try:
    from fmp_compat import fmp_get, get_fmp_keys
except ImportError:  # standalone .skill install without the repo-root module
    fmp_get = None

    def get_fmp_keys():
        return []


# --- FMP endpoint: stable only. FMP retired v3 for non-legacy keys on
# 2025-08-31; a v3 URL requested through fmp_compat is rewritten back to the
# equivalent stable endpoint anyway (see `_V3_TO_STABLE` in the repo-root
# fmp_compat.py), so a second "v3 fallback" entry here was never a distinct
# endpoint — it was a second, rate-limited query of the SAME stable endpoint
# plus a misleading WARN line (WPP-20260827-012). The cross-provider fallback
# is yfinance, wired into the callers below. ---


def _stable_quote_url(base, symbols_str, params):
    """stable/quote?symbol=^GSPC"""
    params["symbol"] = symbols_str
    return base, params


def _stable_hist_url(base, symbols_str, params):
    """stable/historical-price-eod/full?symbol=^GSPC&from=...&to=..."""
    params["symbol"] = symbols_str
    # New stable EOD endpoint ignores `timeseries`; convert to from/to range
    # to bound the payload. Use 2x calendar days to cover N trading days
    # (trading-day/calendar-day ratio ~252/365 ~0.69, so *2 leaves headroom).
    days = params.pop("timeseries", None)
    if days is not None:
        today = date.today()
        params["from"] = (today - timedelta(days=int(days) * 2)).isoformat()
        params["to"] = today.isoformat()
    return base, params


_FMP_ENDPOINTS = {
    "quote": [
        ("https://financialmodelingprep.com/stable/quote", _stable_quote_url),
    ],
    "historical": [
        ("https://financialmodelingprep.com/stable/historical-price-eod/full", _stable_hist_url),
    ],
}


def _normalize_eod_flat_list(data, symbols_str: str, limit: Optional[int] = None):
    """Convert stable/historical-price-eod/full flat list to v3-compatible dict.

    Input  : [{"symbol": "SPY", "date": "...", "open": ..., ...}, ...]
    Output : {"symbol": "SPY", "historical": [{"date": ..., "open": ..., ...}, ...]}

    Returns the input unchanged if not a list (passthrough for the dict /
    historicalStockList shapes the stable batch format can still return).
    Returns None when no row matches the
    requested symbol; the caller will record the failure and try the next
    endpoint.

    If `limit` is provided (the original `timeseries=N` request), the
    `historical` list is truncated to the first `limit` entries. The new
    EOD endpoint ignores `timeseries` and returns the full available history,
    so the caller's date-range bounding plus this truncation together preserve
    the legacy "most-recent N rows" contract. Truncation assumes descending
    date order, which the FMP EOD endpoint provides (verified live).

    Note: empty list ``[]`` does not reach this normalizer because the caller's
    ``if not data: continue`` falsy check handles it earlier in
    ``_request_with_fallback``.
    """
    if not isinstance(data, list):
        return data
    if not data:
        return None
    norm_target = symbols_str.replace("-", ".")
    matched_symbol = None
    historical = []
    for row in data:
        if not isinstance(row, dict):
            continue
        # Be permissive: single-symbol endpoint may omit per-row "symbol".
        # Treat missing symbol as belonging to the requested symbols_str.
        row_sym = row.get("symbol") or symbols_str
        if row_sym.replace("-", ".") != norm_target:
            continue
        matched_symbol = matched_symbol or row_sym
        historical.append({k: v for k, v in row.items() if k != "symbol"})
    if not historical:
        return None
    if limit is not None and limit > 0:
        historical = historical[:limit]
    return {"symbol": matched_symbol or symbols_str, "historical": historical}


# --- WPP-20260827-009: value boundary for every provider (policy of WPP-20260818-009) ---
#
# `float(row["Close"])` passes NaN straight through — `bool(float("nan")) is
# True` — and downstream, NaN fails EVERY comparison: distribution-day counting
# compares closes and volumes positionally, and `_yf_quote` derives yearHigh via
# `max()` over the window, where a NaN in the FIRST bar seeds `max` and yields
# NaN while a later NaN is silently skipped — quietly wrong rather than visibly
# broken. The rule, stated once: no missing or non-finite observation may be
# converted into a value that reads as a valid one. Reject the whole fetch and
# let the caller's existing degrade path run; never repair a field, never drop
# a single bar (positional consumers would compare non-adjacent sessions).
#
# Date ORDER is not re-proven here: after the v3 sunset the only providers are
# stable EOD (descending — verified live) and yfinance (built ascending, then
# reversed below), both order-guaranteed by construction. This boundary
# validates VALUES, all-or-none per fetch.


def _finite(value) -> bool:
    """True for a real, finite number. `bool` is not a price.

    `math.isfinite` RAISES `OverflowError` on a Python int beyond float range,
    so an unguarded call turns malformed data into a crash instead of a
    rejection. A predicate that can raise is not a predicate.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return False
    try:
        return math.isfinite(value)
    except OverflowError:
        return False


def _finite_positive(value) -> bool:
    """True for a real, finite, strictly positive number."""
    return _finite(value) and value > 0


def _quote_values_ok(quote) -> bool:
    """A quote is an observation iff `price` is real and positive AND every
    load-bearing 52-week field it CARRIES is too.

    `yearHigh`/`yearLow` feed the 52-week-distance signal and leading-stock
    basket selection (`quote.get("yearHigh", 0)`) — a present NaN suppresses or
    poisons that signal and a present None raises, while a price-only check
    accepts both (codex gate r1). Absent fields stay acceptable: consumers see
    the absence; they cannot see a bad value.
    """
    if not _finite_positive(quote.get("price")):
        return False
    for key in ("yearHigh", "yearLow"):
        if key in quote and not _finite_positive(quote.get(key)):
            return False
    return True


def _history_values_ok(payload) -> bool:
    """All-or-none value check over a normalized ``historical`` payload.

    Every bar must carry finite, strictly positive open/high/low/close and a
    finite, non-negative volume. One bad bar rejects the whole payload —
    positional consumers (distribution-day counting) must never see a spliced
    series, and a substituted 0.0 would read as a valid observation.
    """
    if not isinstance(payload, dict):
        return False
    bars = payload.get("historical")
    if not isinstance(bars, list) or not bars:
        return False
    for bar in bars:
        if not isinstance(bar, dict):
            return False
        if not all(_finite_positive(bar.get(k)) for k in ("open", "high", "low", "close")):
            return False
        # A PRESENT adjClose must be real too — downstream consumers prefer it
        # over close (e.g. `d.get("close", d.get("adjClose", 0))` fallbacks and
        # macro's monthly downsampling), so a present NaN/None/0 adjClose would
        # sail past a close-only check and poison the series (codex gate r1).
        # An ABSENT adjClose stays acceptable: absence is visible to consumers,
        # a bad value is not.
        if "adjClose" in bar and not _finite_positive(bar.get("adjClose")):
            return False
        vol = bar.get("volume")
        if not _finite(vol) or vol < 0:
            return False
    return True


def _yf_history(symbol: str, days: int) -> Optional[dict]:
    """Fetch daily history via yfinance and normalize to FMP historical shape.

    Returns ``{"symbol": ..., "historical": [...]}`` with most-recent-first
    bars (date/open/high/low/close/adjClose/volume), or ``None`` on
    empty/error. ``yfinance`` is imported lazily so the FMP success path never
    depends on it. Any bar with a non-finite price or volume rejects the WHOLE
    fetch (WPP-20260827-009) — the caller's degrade path handles None.
    """
    try:
        import yfinance as yf

        end = date.today()
        start = end - timedelta(days=int(days * 1.5))  # cover weekends/holidays
        df = yf.download(
            symbol,
            start=start.isoformat(),
            end=end.isoformat(),
            auto_adjust=True,
            progress=False,
        )
        if df is None or df.empty:
            return None
        # yfinance returns MultiIndex columns for a single ticker.
        if hasattr(df.columns, "levels"):
            df.columns = df.columns.droplevel(1)
        historical = []
        for idx, row in df.iterrows():
            o = float(row["Open"])
            h = float(row["High"])
            low = float(row["Low"])
            close = float(row["Close"])
            try:
                vol = float(row["Volume"])
            except (TypeError, ValueError):
                vol = float("nan")
            if not (
                all(_finite_positive(v) for v in (o, h, low, close)) and _finite(vol) and vol >= 0
            ):
                print(
                    f"WARNING: yfinance returned a non-finite bar for {symbol} "
                    f"at {idx.strftime('%Y-%m-%d')}; rejecting the whole fetch "
                    "(no repair, no trim — WPP-20260827-009)",
                    file=sys.stderr,
                )
                return None
            historical.append(
                {
                    "date": idx.strftime("%Y-%m-%d"),
                    "open": o,
                    "high": h,
                    "low": low,
                    "close": close,
                    "adjClose": close,  # auto_adjust=True -> Close already adjusted
                    "volume": int(vol),
                }
            )
        if not historical:
            return None
        historical.reverse()  # yfinance ascending -> FMP most-recent-first
        return {"symbol": symbol, "historical": historical[:days], "data_source": "yfinance"}
    except Exception as e:
        print(f"WARNING: yfinance history fallback failed for {symbol}: {e}", file=sys.stderr)
        return None


def _yf_quote(symbol: str) -> Optional[dict]:
    """Quote-like record derived from recent yfinance daily bars (FMP quote shape).

    Year high/low are approximated from ~252 daily bars. The `max()`/`min()`
    below are NaN-safe by invariant: `_yf_history` validates every bar
    all-or-none (WPP-20260827-009), so the window is either entirely finite or
    this function never runs — the previous order-dependent-NaN failure mode
    (NaN seeding `max` from bar 0, silently skipped later) is unreachable.
    """
    hist = _yf_history(symbol, 260)
    if not hist or not hist.get("historical"):
        return None
    bars = hist["historical"]  # most-recent-first
    latest = bars[0]
    prev_close = bars[1]["close"] if len(bars) > 1 else latest["close"]
    price = latest["close"]
    change = price - prev_close
    pct = (change / prev_close * 100) if prev_close else 0.0
    window = bars[:252]
    year_high = max(b["high"] for b in window)
    year_low = min(b["low"] for b in window)
    return {
        "symbol": symbol,
        "price": price,
        "previousClose": prev_close,
        "change": change,
        "changesPercentage": pct,
        "open": latest["open"],
        "high": latest["high"],
        "low": latest["low"],
        "volume": latest["volume"],
        "yearHigh": year_high,
        "yearLow": year_low,
        "data_source": "yfinance",
    }


class FMPClient:
    """Client for Financial Modeling Prep API with rate limiting and caching"""

    BASE_URL = "https://financialmodelingprep.com/api/v3"
    RATE_LIMIT_DELAY = 0.3  # 300ms between requests

    _ENDPOINT_FAILURE_THRESHOLD = 3  # disable endpoint after N consecutive failures

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("FMP_API_KEY")
        # In standalone yf-only mode (fmp_get is None) no FMP call can ever be
        # made, so a missing key must not abort construction — this ValueError
        # was the SECOND way a bare .skill install died before reaching the
        # yfinance fallback (WPP-20260831-001 corollary).
        if not self.api_key and fmp_get is not None:
            raise ValueError(
                "FMP API key required. Set FMP_API_KEY environment variable "
                "or pass api_key parameter."
            )
        self.session = requests.Session()
        if self.api_key:
            self.session.headers.update({"apikey": self.api_key})
        self.cache = {}
        self.last_call_time = 0
        self.rate_limit_reached = False
        self.retry_count = 0
        self.max_retries = 1
        self.api_calls_made = 0
        # Circuit breaker: track consecutive failures per endpoint URL prefix
        self._endpoint_failures: dict[str, int] = {}
        self._disabled_endpoints: set[str] = set()
        self.data_sources: dict[str, str] = {}

    def _rate_limited_get(
        self, url: str, params: Optional[dict] = None, quiet: bool = False
    ) -> Optional[dict]:
        if self.rate_limit_reached:
            return None

        if params is None:
            params = {}

        elapsed = time.time() - self.last_call_time
        if elapsed < self.RATE_LIMIT_DELAY:
            time.sleep(self.RATE_LIMIT_DELAY - elapsed)

        if fmp_get is None:
            # Standalone .skill install: the repo-root fmp_compat transport is
            # absent, so FMP is typed-unavailable and the yfinance fallback is
            # the only provider. WARN once, then quietly return misses.
            if not getattr(self, "_warned_no_fmp_compat", False):
                print(
                    "WARNING: fmp_compat unavailable (standalone install) — "
                    "FMP disabled, running yfinance-only",
                    file=sys.stderr,
                )
                self._warned_no_fmp_compat = True
            return None

        data = fmp_get(url, params=params, timeout=30, max_retries_per_key=1)
        self.last_call_time = time.time()
        self.api_calls_made += 1
        if data is None and not quiet:
            if not get_fmp_keys():
                print(
                    "ERROR: FMP keys not in environment — likely a source/export bug, not a quota issue",
                    file=sys.stderr,
                )
            else:
                print(f"ERROR: FMP request failed or quota-limited: {url}", file=sys.stderr)
        return data

    def _request_with_fallback(self, endpoint_key, symbols_str, extra_params=None):
        """Query the stable FMP endpoint; the loop shape stays even though the
        endpoint list is now a single entry (WPP-20260827-012 — stable is the
        only FMP endpoint; through fmp_compat, a v3 URL was rewritten back to
        stable anyway, so a second v3 leg here would just be a second,
        rate-limited query of the same endpoint). The cross-provider fallback
        is yfinance, wired into the callers below.

        Returns parsed JSON in the historical/quote shape callers expect, or
        None if the endpoint fails.
        """
        params = dict(extra_params) if extra_params else {}
        endpoints = _FMP_ENDPOINTS[endpoint_key]
        is_single = "," not in symbols_str

        for i, (base_url, url_builder) in enumerate(endpoints):
            # Circuit breaker: skip endpoints with too many consecutive failures
            if base_url in self._disabled_endpoints:
                continue

            url, final_params = url_builder(base_url, symbols_str, dict(params))
            is_last = i == len(endpoints) - 1
            data = self._rate_limited_get(url, final_params, quiet=not is_last)
            if not data:  # falsy (None, [], {}) — try next endpoint
                self._record_endpoint_failure(base_url)
                continue

            # Normalize new stable EOD flat-list shape to v3-compatible dict.
            # No-op for v3 dict / historicalStockList responses.
            # `timeseries` (original request) is passed as `limit` so the
            # EOD endpoint's full-history response is truncated to the
            # legacy "most-recent N rows" contract.
            if endpoint_key == "historical":
                limit = params.get("timeseries") if isinstance(params, dict) else None
                data = _normalize_eod_flat_list(data, symbols_str, limit=limit)
                if not data:
                    self._record_endpoint_failure(base_url)
                    continue

            # Shape validation: reject truthy-but-wrong-shape responses
            valid = True
            if endpoint_key == "quote":
                if not isinstance(data, list) or len(data) == 0:
                    valid = False
                elif is_single and not any(
                    q.get("symbol", "").replace("-", ".") == symbols_str.replace("-", ".")
                    for q in data
                ):
                    valid = False
                else:
                    # Identity BEFORE price (ftd gate-r3 lesson): for a
                    # single-symbol request, narrow to rows matching the
                    # requested symbol first — a symbol-omitting row on a
                    # single-symbol endpoint belongs to the request.
                    # Price-filtering first could drop the requested row and
                    # hand the caller an unrelated security as element [0].
                    candidates = data
                    if is_single:
                        norm = symbols_str.replace("-", ".")
                        candidates = [
                            q
                            for q in candidates
                            if isinstance(q, dict)
                            and (q.get("symbol") or symbols_str).replace("-", ".") == norm
                        ]
                    # WPP-20260827-009 value boundary: a quote without a real,
                    # positive price is not a quote. Quotes are independent
                    # per-symbol records, so filtering (unlike bar-splicing in a
                    # time series) removes nothing positional.
                    kept_quotes = [
                        q for q in candidates if isinstance(q, dict) and _quote_values_ok(q)
                    ]
                    if not kept_quotes:
                        print(
                            f"WARNING: FMP quote payload for {symbols_str} carried no "
                            "matching quote with a real, positive price; rejecting "
                            "(WPP-20260827-009)",
                            file=sys.stderr,
                        )
                        valid = False
                    else:
                        data = kept_quotes

            if endpoint_key == "historical":
                if not isinstance(data, dict):
                    valid = False
                elif "historicalStockList" in data:
                    # stable batch format -> v3 single format (exact match only)
                    norm = symbols_str.replace("-", ".")
                    found = None
                    for entry in data["historicalStockList"]:
                        if entry.get("symbol", "").replace("-", ".") == norm:
                            found = {
                                "symbol": entry.get("symbol"),
                                "historical": entry.get("historical", []),
                            }
                            break
                    if found:
                        if _history_values_ok(found):
                            self._endpoint_failures[base_url] = 0
                            return found
                        print(
                            f"WARNING: FMP batch history for {symbols_str} failed the "
                            "value boundary (non-finite or non-positive field); "
                            "rejecting the payload (WPP-20260827-009)",
                            file=sys.stderr,
                        )
                    valid = False
                elif "historical" not in data:
                    valid = False
                elif is_single and data.get("symbol"):
                    if data["symbol"].replace("-", ".") != symbols_str.replace("-", "."):
                        valid = False
                # WPP-20260827-009 value boundary: FMP JSON can carry bare NaN
                # (json.loads accepts it) and _normalize_eod_flat_list copies
                # row values verbatim — all-or-none, same rule as the yf path.
                # The rejection must be as loud as the yf-side one: an operator
                # debugging a missing signal has to be able to tell "the guard
                # caught bad data" from "the endpoint was unreachable".
                if valid and not _history_values_ok(data):
                    print(
                        f"WARNING: FMP history for {symbols_str} failed the value "
                        "boundary (non-finite or non-positive field); rejecting the "
                        "payload (WPP-20260827-009)",
                        file=sys.stderr,
                    )
                    valid = False

            if valid:
                self._endpoint_failures[base_url] = 0
                return data
            self._record_endpoint_failure(base_url)
        return None

    def _record_endpoint_failure(self, base_url: str) -> None:
        """Track consecutive failures and disable endpoint after threshold."""
        failures = self._endpoint_failures.get(base_url, 0) + 1
        self._endpoint_failures[base_url] = failures
        if (
            failures >= self._ENDPOINT_FAILURE_THRESHOLD
            and base_url not in self._disabled_endpoints
        ):
            self._disabled_endpoints.add(base_url)
            print(
                f"WARNING: FMP endpoint disabled for the rest of this run after "
                f"{failures} consecutive failures: {base_url}",
                file=sys.stderr,
            )

    def get_quote(self, symbols: str) -> Optional[list[dict]]:
        """Fetch real-time quote data for one or more symbols (comma-separated).

        Falls back to a yfinance-derived quote when FMP returns nothing (e.g. an
        index like ^GSPC/^VIX gated behind a paid FMP plan). Fallback is
        single-symbol only — comma lists are left to FMP.
        """
        cache_key = f"quote_{symbols}"
        if cache_key in self.cache:
            return self.cache[cache_key]

        data = self._request_with_fallback("quote", symbols)
        if not data:
            quotes = []
            for symbol in symbols.split(","):
                quote = _yf_quote(symbol)
                if quote:
                    quotes.append(quote)
                    self.data_sources[f"quote:{symbol}"] = "yfinance"
            data = quotes or None
        else:
            for symbol in symbols.split(","):
                self.data_sources[f"quote:{symbol}"] = "fmp"
        if data:
            self.cache[cache_key] = data
        return data

    def get_historical_prices(self, symbol: str, days: int = 365) -> Optional[dict]:
        """Fetch historical daily OHLCV data.

        Falls back to yfinance when the FMP endpoint returns no usable history
        (e.g. an index/ETF gated behind a paid FMP plan). The yfinance path
        needs no extra API key; an FMP key is still required to build the client.
        """
        cache_key = f"prices_{symbol}_{days}"
        if cache_key in self.cache:
            return self.cache[cache_key]

        data = self._request_with_fallback("historical", symbol, {"timeseries": days})
        if not data:
            data = _yf_history(symbol, days)
            if data:
                self.data_sources[f"historical:{symbol}"] = "yfinance"
        else:
            data["data_source"] = data.get("data_source", "fmp")
            self.data_sources[f"historical:{symbol}"] = data["data_source"]
        if data:
            self.cache[cache_key] = data
            return data
        return None

    def get_batch_quotes(self, symbols: list[str]) -> dict[str, dict]:
        """Fetch quotes for a list of symbols.

        Note: The FMP `/stable/quote` endpoint only accepts a single symbol per
        call. Passing comma-separated symbols silently returns []. The
        deprecated `/api/v3/quote/A,B,C` batch syntax now returns 403 for
        non-legacy keys (retired Aug 31, 2025). So we iterate one symbol at a
        time. Rate limiting in `_rate_limited_get` keeps this within plan
        limits.
        """
        results = {}
        for symbol in symbols:
            quotes = self.get_quote(symbol)
            if quotes:
                for q in quotes:
                    if q.get("symbol"):
                        results[q["symbol"]] = q
        return results

    def get_batch_historical(self, symbols: list[str], days: int = 50) -> dict[str, list[dict]]:
        """Fetch historical prices for multiple symbols"""
        results = {}
        for symbol in symbols:
            data = self.get_historical_prices(symbol, days=days)
            if data and "historical" in data:
                results[symbol] = data["historical"]
        return results

    def calculate_ema(self, prices: list[float], period: int) -> float:
        """Calculate EMA (thin wrapper around math_utils for backward compat)."""
        from calculators.math_utils import calc_ema

        return calc_ema(prices, period)

    def calculate_sma(self, prices: list[float], period: int) -> float:
        """Calculate SMA (thin wrapper around math_utils for backward compat)."""
        from calculators.math_utils import calc_sma

        return calc_sma(prices, period)

    def get_vix_term_structure(self) -> Optional[dict]:
        """
        Auto-detect VIX term structure by comparing VIX to VIX3M.

        Returns:
            Dict with ratio, classification, or None if VIX3M unavailable.
        """
        vix_quotes = self.get_quote("^VIX")
        vix3m_quotes = self.get_quote("^VIX3M")

        if not vix_quotes or not vix3m_quotes:
            return None

        vix_price = vix_quotes[0].get("price", 0)
        vix3m_price = vix3m_quotes[0].get("price", 0)

        if vix3m_price <= 0:
            return None

        ratio = vix_price / vix3m_price

        if ratio < 0.85:
            classification = "steep_contango"
        elif ratio < 0.95:
            classification = "contango"
        elif ratio <= 1.05:
            classification = "flat"
        else:
            classification = "backwardation"

        return {
            "vix": round(vix_price, 2),
            "vix3m": round(vix3m_price, 2),
            "ratio": round(ratio, 3),
            "classification": classification,
        }

    def get_api_stats(self) -> dict:
        return {
            "cache_entries": len(self.cache),
            "api_calls_made": self.api_calls_made,
            "rate_limit_reached": self.rate_limit_reached,
            "data_sources": self.data_sources,
        }
