#!/usr/bin/env python3
# GENERATED by scripts/generate_fmp_client.py — do not edit.
# Source of truth: scripts/fmp_client/ (core_template.py.tmpl, registry.py, extensions/).
# Regenerate: python3 scripts/generate_fmp_client.py
"""
FMP API Client for VCP Screener

Provides rate-limited access to Financial Modeling Prep API endpoints.

Features:
- Rate limiting (0.3s between requests)
- Automatic key failover via fmp_compat (repo-root transport)
- Session caching for duplicate requests
- Batch quote support
- S&P 500 constituents fetching
"""

import os
import sys
import time
from pathlib import Path
from typing import Optional

try:
    import requests
except ImportError:
    print("ERROR: requests library not found. Install with: pip install requests", file=sys.stderr)
    sys.exit(1)

SKILL_ROOT = Path(__file__).resolve().parents[3]
if str(SKILL_ROOT) not in sys.path:
    sys.path.insert(0, str(SKILL_ROOT))

try:
    from fmp_compat import fmp_get_typed, key_override
except ImportError:  # standalone .skill install without the repo-root module
    fmp_get_typed = None


# --- FMP endpoint: stable only. FMP retired v3 for non-legacy keys on
# 2025-08-31; a v3 URL requested through fmp_compat is rewritten back to the
# equivalent stable endpoint anyway (see `_V3_TO_STABLE` in the repo-root
# fmp_compat.py), so a second "v3 fallback" entry here was never a distinct
# endpoint — it was a second, rate-limited query of the SAME stable endpoint
# (WPP-20260827-012). ---


def _stable_quote_url(base, symbols_str, params):
    """stable/quote?symbol=^GSPC"""
    params["symbol"] = symbols_str
    return base, params


def _stable_hist_url(base, symbols_str, params):
    """stable/historical-price-eod/full?symbol=^GSPC&timeseries=80

    `timeseries` is passed through unchanged — fmp_compat's own
    `_prepare_params_for_url` converts it into a from/to range plus an
    internal `_tm_limit` truncation bound before the request is made.
    """
    params["symbol"] = symbols_str
    return base, params


_FMP_ENDPOINTS = {
    "quote": [
        ("https://financialmodelingprep.com/stable/quote", _stable_quote_url),
    ],
    "historical": [
        ("https://financialmodelingprep.com/stable/historical-price-eod/full", _stable_hist_url),
    ],
}


class FMPClient:
    """Client for Financial Modeling Prep API with rate limiting and caching"""

    BASE_URL = "https://financialmodelingprep.com/api/v3"
    RATE_LIMIT_DELAY = 0.3  # 300ms between requests

    _ENDPOINT_FAILURE_THRESHOLD = 3  # disable endpoint after N consecutive failures

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("FMP_API_KEY")
        if not self.api_key:
            raise ValueError(
                "FMP API key required. Set FMP_API_KEY environment variable "
                "or pass api_key parameter."
            )
        self.cache = {}
        self.last_call_time = 0
        self.rate_limit_reached = False
        self.retry_count = 0
        self.max_retries = 1
        self.api_calls_made = 0
        # Circuit breaker: track consecutive failures per endpoint URL prefix
        self._endpoint_failures: dict[str, int] = {}
        self._disabled_endpoints: set[str] = set()
        # Most recent transport-level failure reason; set by _rate_limited_get
        # so _request_with_fallback can surface suppressed errors even when
        # an endpoint was called with quiet=True.
        self._last_error: Optional[str] = None

    def _raw_stable_get(self, url: str, params: dict) -> Optional[dict]:
        """Thin standalone fallback when fmp_compat is not importable — a
        `.skill` archive bundles this file but not the repo-root
        `fmp_compat.py` (verified via `unzip -l`). One request, no key
        failover, no v3 rung; sets `_last_error` on any miss."""
        try:
            response = requests.get(url, params={**params, "apikey": self.api_key}, timeout=30)
            if response.status_code == 200:
                return response.json()
        except (requests.exceptions.RequestException, ValueError):
            pass
        self._last_error = "fmp_compat unavailable: raw stable GET, no failover"
        return None

    def _rate_limited_get(
        self, url: str, params: Optional[dict] = None, quiet: bool = False
    ) -> Optional[dict]:
        self._last_error = None
        if self.rate_limit_reached:
            self._last_error = "daily rate limit already reached"
            return None

        if params is None:
            params = {}

        elapsed = time.time() - self.last_call_time
        if elapsed < self.RATE_LIMIT_DELAY:
            time.sleep(self.RATE_LIMIT_DELAY - elapsed)

        if fmp_get_typed is None:
            if not getattr(self, "_warned_no_fmp_compat", False):
                print(
                    "WARNING: fmp_compat unavailable (standalone install) — "
                    "using a single stable GET with no key failover",
                    file=sys.stderr,
                )
                self._warned_no_fmp_compat = True
            self.last_call_time = time.time()
            self.api_calls_made += 1
            return self._raw_stable_get(url, params)

        # A caller-supplied key differing from the ambient FMP_API_KEY is
        # scoped to this call only; FMP_FALLBACK_API_KEY is never touched.
        override = self.api_key if self.api_key != os.environ.get("FMP_API_KEY") else None
        with key_override(override):
            data, reason = fmp_get_typed(url, params=params, timeout=30, max_retries_per_key=1)
        self.api_calls_made += 1
        self.last_call_time = time.time()
        self._last_error = reason
        if data is None:
            # Only the 429 daily-quota signal latches the run-wide breaker;
            # 402/403/soft-quota is usually a free-tier entitlement gap and
            # `unreachable` is a transport blip — neither should stop the run.
            if reason == "rate_limited:429":
                self.rate_limit_reached = True
            if not quiet:
                print(f"ERROR: {url} failed ({reason})", file=sys.stderr)
        return data

    def _request_with_fallback(self, endpoint_key, symbols_str, extra_params=None):
        """Query the stable FMP endpoint(s); the loop shape stays even though
        each endpoint list is now a single entry (fmp_compat already rewrites
        a v3 URL back to the identical stable endpoint, so a second "v3
        fallback" rung was never a distinct endpoint — WPP-20260827-012).
        Non-last endpoints are called with quiet=True so the user isn't
        alarmed by an expected failure when another entry will catch it — but
        when a non-last endpoint DOES fail, a WARN line is emitted explaining
        why we're falling back. Otherwise users only see the (often misleading)
        last-endpoint error and have no clue what really went wrong.
        """
        params = dict(extra_params) if extra_params else {}
        endpoints = _FMP_ENDPOINTS[endpoint_key]
        is_single = "," not in symbols_str

        for i, (base_url, url_builder) in enumerate(endpoints):
            # Circuit breaker: skip endpoints with too many consecutive failures
            if base_url in self._disabled_endpoints:
                continue

            url, final_params = url_builder(base_url, symbols_str, dict(params))
            is_last = i == len(endpoints) - 1
            data = self._rate_limited_get(url, final_params, quiet=not is_last)
            if not data:  # falsy (None, [], {}) — try next endpoint
                self._record_endpoint_failure(base_url)
                self._warn_fallback(base_url, is_last, self._last_error)
                continue

            # Shape validation: reject truthy-but-wrong-shape responses
            valid = True
            shape_issue: Optional[str] = None
            if endpoint_key == "quote":
                if not isinstance(data, list) or len(data) == 0:
                    valid = False
                    shape_issue = "expected non-empty list"
                elif is_single and not any(
                    q.get("symbol", "").replace("-", ".") == symbols_str.replace("-", ".")
                    for q in data
                ):
                    valid = False
                    shape_issue = f"requested symbol '{symbols_str}' not in response"

            if endpoint_key == "historical":
                if not isinstance(data, dict):
                    valid = False
                    shape_issue = "expected dict"
                elif "historicalStockList" in data:
                    # stable batch format -> v3 single format (exact match only)
                    norm = symbols_str.replace("-", ".")
                    found = None
                    for entry in data["historicalStockList"]:
                        if entry.get("symbol", "").replace("-", ".") == norm:
                            found = {
                                "symbol": entry.get("symbol"),
                                "historical": entry.get("historical", []),
                            }
                            break
                    if found:
                        self._endpoint_failures[base_url] = 0
                        return found
                    valid = False
                    shape_issue = f"'{symbols_str}' not in historicalStockList"
                elif "historical" not in data:
                    valid = False
                    shape_issue = "missing 'historical' key"
                elif is_single and data.get("symbol"):
                    if data["symbol"].replace("-", ".") != symbols_str.replace("-", "."):
                        valid = False
                        shape_issue = (
                            f"response symbol '{data['symbol']}' != requested '{symbols_str}'"
                        )

            if valid:
                self._endpoint_failures[base_url] = 0
                return data
            self._record_endpoint_failure(base_url)
            self._warn_fallback(base_url, is_last, shape_issue or "unexpected response shape")
        return None

    def _warn_fallback(self, base_url: str, is_last: bool, reason: Optional[str]) -> None:
        """Emit a WARN line so users see why a non-last endpoint failed and the
        client is falling back. No-op when the failing endpoint is the last one
        (its error was already printed by _rate_limited_get with quiet=False)."""
        if is_last or not reason:
            return
        print(
            f"WARN: {base_url} failed ({reason}); falling back to next endpoint",
            file=sys.stderr,
        )

    def _record_endpoint_failure(self, base_url: str) -> None:
        """Track consecutive failures and disable endpoint after threshold."""
        failures = self._endpoint_failures.get(base_url, 0) + 1
        self._endpoint_failures[base_url] = failures
        if failures >= self._ENDPOINT_FAILURE_THRESHOLD:
            self._disabled_endpoints.add(base_url)

    # Public-dataset fallback for keys where no FMP tier serves constituents:
    # /stable/sp500-constituent 402s (Restricted Endpoint) on the free tier
    # and /api/v3/sp500_constituent 403s (Legacy Endpoint) for keys created
    # after 2025-08-31.
    _CONSTITUENTS_CSV_URL = (
        "https://raw.githubusercontent.com/datasets/"
        "s-and-p-500-companies/main/data/constituents.csv"
    )

    def _fetch_constituents_csv(self) -> Optional[list[dict]]:
        """Fetch the public S&P 500 list, mapped to the v3 response shape.

        Uses a bare requests.get, NOT self.session — the FMP apikey header
        must not leak to a third-party host.
        """
        import csv
        import io

        try:
            response = requests.get(self._CONSTITUENTS_CSV_URL, timeout=30)
            if response.status_code != 200:
                print(
                    f"ERROR: constituents CSV fallback failed: {response.status_code}",
                    file=sys.stderr,
                )
                return None
            data = [
                {
                    # FMP uses dash-style class symbols (BRK-B), the CSV uses dots.
                    "symbol": row["Symbol"].replace(".", "-"),
                    "name": row["Security"],
                    "sector": row["GICS Sector"],
                    "subSector": row["GICS Sub-Industry"],
                }
                for row in csv.DictReader(io.StringIO(response.text))
                if row.get("Symbol")
            ]
        except (requests.exceptions.RequestException, csv.Error, KeyError) as e:
            print(f"ERROR: constituents CSV fallback failed: {e}", file=sys.stderr)
            return None
        return data or None

    def get_sp500_constituents(self) -> Optional[list[dict]]:
        """Fetch S&P 500 constituent list.

        Returns:
            List of dicts with keys: symbol, name, sector, subSector
            or None on failure.
        """
        cache_key = "sp500_constituents"
        if cache_key in self.cache:
            return self.cache[cache_key]

        url = "https://financialmodelingprep.com/stable/sp500-constituent"
        data = self._rate_limited_get(url, {})
        if not data:
            # No FMP tier serves this list on some keys (402 on stable, 403
            # on v3) — fall back to the public dataset.
            data = self._fetch_constituents_csv()
        if data:
            self.cache[cache_key] = data
        return data

    def get_quote(self, symbols: str) -> Optional[list[dict]]:
        """Fetch real-time quote data for one or more symbols (comma-separated)"""
        cache_key = f"quote_{symbols}"
        if cache_key in self.cache:
            return self.cache[cache_key]

        data = self._request_with_fallback("quote", symbols)
        if data:
            self.cache[cache_key] = data
        return data

    def get_batch_quotes(self, symbols: list[str]) -> dict[str, dict]:
        """Fetch quotes for a list of symbols.

        `/stable/quote` does not support comma-batched symbols (verified live:
        `?symbol=AAPL,MSFT` returns None; a single symbol returns one row), so
        each symbol is requested individually.
        """
        results = {}
        for symbol in symbols:
            quotes = self.get_quote(symbol)
            if quotes:
                for q in quotes:
                    results[q["symbol"]] = q
        return results

    def get_batch_historical(self, symbols: list[str], days: int = 260) -> dict[str, list[dict]]:
        """Fetch historical prices for multiple symbols"""
        results = {}
        for symbol in symbols:
            data = self.get_historical_prices(symbol, days=days)
            if data and "historical" in data:
                results[symbol] = data["historical"]
        return results

    def calculate_sma(self, prices: list[float], period: int) -> float:
        """Calculate Simple Moving Average from a list of prices (most recent first)"""
        if len(prices) < period:
            return sum(prices) / len(prices)
        return sum(prices[:period]) / period

    def get_historical_prices(self, symbol: str, days: int = 365) -> Optional[dict]:
        """Fetch historical daily OHLCV data.

        Args:
            symbol: Stock symbol
            days: Number of trading days to fetch

        Returns:
            Dict with 'symbol' and 'historical' keys, where 'historical' is a
            list of price dicts (most-recent-first) with: date, open, high, low,
            close, adjClose, volume
        """
        cache_key = f"prices_{symbol}_{days}"
        if cache_key in self.cache:
            return self.cache[cache_key]

        data = self._request_with_fallback("historical", symbol, {"timeseries": days})
        if data:
            self.cache[cache_key] = data
        return data

    def get_api_stats(self) -> dict:
        """Return API usage statistics."""
        return {
            "cache_entries": len(self.cache),
            "api_calls_made": self.api_calls_made,
            "rate_limit_reached": self.rate_limit_reached,
        }
